MODEL:
  META_ARCHITECTURE: "CondInst"
  MASK_ON: True
  BACKBONE:
    NAME: "build_fcos_resnet_fpn_backbone"
  RESNETS:
    OUT_FEATURES: ["res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res3", "res4", "res5"]
  PROPOSAL_GENERATOR:
    NAME: "FCOS"
  FCOS:
    THRESH_WITH_CTR: True
    USE_SCALE: True
  CONDINST:
    MAX_PROPOSALS: 500
DATASETS:
  TRAIN: ("pannuke_in_mscoco_format_train",)
  TEST: ("pannuke_in_mscoco_format_test",)
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.001
  STEPS: (6, 8)
  MAX_ITER: 9
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
